### PR TITLE
Adding indicator history chart (grouping hourly average)

### PR DESCRIPTION
**Pull request by isaqueveras**
image
image

### CODE REVIEW

**Comment by isaqueveras** [comment]
image

**Comment by iurynogueira** [comment]
Can you create a new view and new end point with this data? I believe that we can keep the other chart to compare values and check the values by mins

**Comment by iurynogueira** [comment]
Your chart is amazing! Good job, this will go help to compare other days in same time.

**Comment by isaqueveras** [comment]
image

**Comment by isaqueveras** [comment]
@iurynogueira your suggestion was made, is pr ready to merge?

**Pull request merged**
